# compiler and flags
CC = gcc
CFLAGS = -Wall -Wextra -std=c11

# list of object files
# OBJECTS = 

# final exe file name
# TARGET = 

# all: $(TARGET)

# $(TARGET): $(OBJECTS)
#	$(CC) $(CFLAGS) -o $@ $^

# %.o: %.c
#	$(CC) $(CFLAGS) -c $< -o $@

# remove .o files
# clean:
#	rm -rf *.o $(TARGET)
